// SPDX-License-Identifier: MIT
pragma solidity 0.8.26;

import {Base} from "./Base.t.sol";
import {GameReserve} from "../src/GameReserve.sol";
import {OpsTreasury} from "../src/OpsTreasury.sol";
import {TimelockedRoles} from "../src/TimelockedRoles.sol";
import {VRFPrizeSource, IVRFCoordinator} from "../src/VRFPrizeSource.sol";
import {DeployLocal} from "../script/DeployLocal.s.sol";
import {DCPToken} from "../src/DCPToken.sol";
import {GameShop} from "../src/GameShop.sol";

/// LABELLED TEST FIXTURE: no cryptographic proof is generated by this coordinator.
contract CoordinatorFixture is IVRFCoordinator {
    uint256 public next = 1;
    bool public unavailable;

    function fail(bool yes) external {
        unavailable = yes;
    }

    function requestRandomWords(Request calldata r) external returns (uint256) {
        require(!unavailable, "subscription unfunded");
        require(r.numWords == 1 && r.requestConfirmations >= 3, "request config");
        require(r.extraArgs.length == 36, "extra args");
        return next++;
    }

    function deliver(VRFPrizeSource source, uint256 id, uint256 word) external {
        uint256[] memory words = new uint256[](1);
        words[0] = word;
        source.rawFulfillRandomWords(id, words);
    }
}

contract ReentrantGasOperator {
    OpsTreasury public treasury;
    bool public reentered;

    constructor(OpsTreasury t) {
        treasury = t;
    }

    receive() external payable {
        (bool sent,) = address(0x9999).call{value: msg.value}("");
        require(sent);
        (reentered,) = address(treasury).call(abi.encodeCall(OpsTreasury.topUpGas, (address(this))));
    }
}

contract HardeningTest is Base {
    CoordinatorFixture coordinator;
    VRFPrizeSource source;

    function setUp() public override {
        super.setUp();
        coordinator = new CoordinatorFixture();
        source = new VRFPrizeSource(address(reserve), address(coordinator), bytes32(uint256(1)), 7, 64);
        _timelock(address(reserve), abi.encodeCall(GameReserve.setRandomnessSource, (address(source))));
    }

    function _request(uint256 e) internal {
        vm.prank(poster);
        reserve.requestDraw(e, keccak256(abi.encode(e, "frozen eligibility fixture")));
    }

    function test_VRFWaitAuthenticateNoRerollLateFulfillmentAndClaims() public {
        uint256 e = reserve.currentEpoch() - 1;
        _request(e);
        vm.expectRevert(GameReserve.NotReady.selector);
        reserve.finalizeDraw(e);
        vm.prank(poster);
        vm.expectRevert(GameReserve.AlreadySet.selector);
        reserve.requestDraw(e, keccak256("changed eligibility"));
        uint256[] memory words = new uint256[](1);
        vm.expectRevert(VRFPrizeSource.Unauthorized.selector);
        source.rawFulfillRandomWords(1, words);
        vm.warp(vm.getBlockTimestamp() + 365 days);
        coordinator.deliver(source, 1, 0); // zero is valid VRF output; no time-dependent reroll
        reserve.finalizeDraw(e);
        (,, bytes32 rnd,,,,,) = reserve.rounds(e);
        coordinator.deliver(source, 1, 99); // duplicate ignored
        (, bytes32 word) = source.result(e);
        assertEq(word, bytes32(0));
        assertEq(rnd, keccak256(abi.encode(address(reserve), block.chainid, e, bytes32(0))));
        bytes32 leaf = keccak256(bytes.concat(keccak256(abi.encode(0, attacker, 20 ether))));
        vm.prank(poster);
        reserve.postRoot(e, leaf, 20 ether);
        _timelock(address(reserve), abi.encodeCall(GameReserve.setPoster, (address(0))));
        reserve.claim(e, 0, attacker, 20 ether, new bytes32[](0));
        assertEq(dcp.balanceOf(attacker), 20 ether);
        vm.expectRevert(GameReserve.AlreadyClaimed.selector);
        reserve.claim(e, 0, attacker, 20 ether, new bytes32[](0));
    }

    function test_UnfundedVRFDoesNotLockSnapshotOrSpendReserve() public {
        coordinator.fail(true);
        uint256 e = reserve.currentEpoch() - 1;
        vm.prank(poster);
        vm.expectRevert("subscription unfunded");
        reserve.requestDraw(e, bytes32(uint256(7)));
        assertEq(reserve.eligibilityHash(e), bytes32(0));
        assertEq(reserve.outstanding(), 0);
        coordinator.fail(false);
        _request(e);
        assertEq(coordinator.next(), 2);
    }

    function test_RequestsAndBackloggedRootsCannotBurstDailyBudget() public {
        uint256 e = reserve.currentEpoch() - 2;
        _request(e);
        vm.prank(poster);
        vm.expectRevert(GameReserve.OverCap.selector);
        reserve.requestDraw(e + 1, bytes32(uint256(8)));
        vm.warp(vm.getBlockTimestamp() + 1 days);
        _request(e + 1);
        coordinator.deliver(source, 2, 456); // fulfill in reverse order
        coordinator.deliver(source, 1, 123);
        reserve.finalizeDraw(e + 1);
        reserve.finalizeDraw(e);
        uint256 cap = reserve.epochCap();
        vm.prank(poster);
        reserve.postRoot(e, bytes32(uint256(1)), cap);
        vm.prank(poster);
        vm.expectRevert(GameReserve.OverCap.selector);
        reserve.postRoot(e + 1, bytes32(uint256(2)), 1);
    }

    function test_BlockhashFixtureUnavailableOnMainnet() public {
        vm.chainId(1);
        vm.prank(poster);
        vm.expectRevert(GameReserve.LocalFixtureOnly.selector);
        reserve.commitSeed(100, keccak256("seed"));
        vm.expectRevert(GameReserve.LocalFixtureOnly.selector);
        reserve.anchor(1);
    }

    function test_ZeroOracleOutputPreservesFunds() public {
        vm.prank(swarm);
        dcp.transfer(address(treasury), 10_000 ether);
        oracle.set(address(dcp), 0);
        vm.expectRevert(OpsTreasury.MinOutTooLow.selector);
        treasury.convert(address(dcp), 10_000 ether, 0);
        assertEq(dcp.balanceOf(address(treasury)), 10_000 ether);
        assertEq(dcp.allowance(address(treasury), address(adapter)), 0);
    }

    function test_WethUsesItsOwnDustAndSpendCaps() public {
        weth.mint(address(treasury), 1 ether);
        treasury.convert(address(weth), 0.01 ether, 19.4 ether);
        assertEq(weth.balanceOf(address(treasury)), 0.99 ether);
        assertEq(weth.allowance(address(treasury), address(adapter)), 0);
        vm.expectRevert(OpsTreasury.OverCap.selector);
        treasury.convert(address(weth), 0.051 ether, 98 ether);
    }

    function test_CouncilCannotRaiseHardGasCapOrSpendEssentialFloor() public {
        OpsTreasury.Params memory p = _params();
        p.gasPerEpoch = 100 ether;
        bytes memory data = abi.encodeCall(OpsTreasury.setParams, (p));
        vm.prank(council);
        treasury.queue(data);
        vm.warp(vm.getBlockTimestamp() + 2 days);
        vm.expectRevert();
        treasury.execute(data);
        assertEq(treasury.gasPerEpoch(), 0.2 ether);
        p = _params();
        p.essentialFloor = 0;
        data = abi.encodeCall(OpsTreasury.setParams, (p));
        vm.prank(council);
        treasury.queue(data);
        vm.warp(vm.getBlockTimestamp() + 2 days);
        vm.expectRevert();
        treasury.execute(data);
        assertEq(treasury.essentialFloor(), 500 ether);
    }

    function test_DeployFixtureUsesArgumentsNotCaller() public {
        DeployLocal script = new DeployLocal();
        vm.startPrank(attacker);
        (DCPToken token, GameReserve r, OpsTreasury t, GameShop shop_) =
            script.deploy(DeployLocal.Config(council, guardian, poster, swarm));
        vm.stopPrank();
        assertEq(token.balanceOf(address(r)), 700_000_000 ether);
        assertEq(token.balanceOf(swarm), 100_000_000 ether);
        assertEq(r.council(), council);
        assertEq(r.poster(), poster);
        assertEq(t.guardian(), guardian);
        assertEq(shop_.treasury(), address(t));
        vm.chainId(1);
        vm.expectRevert("local only");
        script.deploy(DeployLocal.Config(council, guardian, poster, swarm));
    }

    function test_GasRecipientCannotReenterAndDrainMultipleTopups() public {
        ReentrantGasOperator malicious = new ReentrantGasOperator(treasury);
        _timelock(address(treasury), abi.encodeCall(OpsTreasury.setGasOperator, (address(malicious), true)));
        vm.deal(address(treasury), 1 ether);
        treasury.topUpGas(address(malicious));
        assertFalse(malicious.reentered());
        assertEq(address(treasury).balance, 0.95 ether);
        assertEq(treasury.gasInEpoch(treasury.epoch()), 0.05 ether);
    }

    function test_OrderFrontRunnerCannotConsumeAnotherBuyerOrder() public {
        bytes32 id = keccak256("victim pending order");
        vm.startPrank(swarm);
        dcp.transfer(attacker, 1 ether);
        dcp.approve(address(shop), 500 ether);
        vm.stopPrank();
        vm.startPrank(attacker);
        dcp.approve(address(shop), 1);
        shop.purchase(id, 1, 1);
        vm.stopPrank();
        vm.prank(swarm);
        shop.purchase(id, 1, 500 ether);
        assertTrue(shop.orderUsed(swarm, id));
        assertTrue(shop.orderUsed(attacker, id));
    }
}
